openapi: "3.1"
info:
  description: |
    The base specification for a Common Knowledge API.
    All Common Knowledge APIs must follow this specification.
    Any Common Knowledge API may extend this specification.
  version: 0.1.0
  title: Common Knowledge API Specification
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: <Your Website>
    description: ""
tags:
  - name: "Conversations"
    description: "Conversations APIs"
  - name: "Generation"
    description: "Generation APIs"
  - name: "Content"
    description: "Content APIs"
  - name: "Meta"
    description: "Meta APIs"
security:
  - NotPartOfSpec: []
paths:
  /openapi:
    get:
      operationId: getOpenApi
      summary: Get Open API specification
      tags:
        - Meta
      description: Get Open API specification for a Common Knowledge API.
      responses:
        200:
          description: The Open API specification of the Common Knowledge API
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenApiSpec"
  /conversations/types:
    get:
      tags:
        - Conversations
      operationId: listConversationTypes
      summary: List conversation types
      description: |
        List different conversation 'personas' types.
        Each has its own set of data sources, system prompts, etc.
      responses:
        200:
          description: List of conversation types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ConversationOverview"
  /conversations/types/{type}:
    post:
      tags:
        - Conversations
      operationId: createConversation
      summary: Create new conversation
      parameters:
        - $ref: "#/components/parameters/ConversationType"
      responses:
        200:
          description: The created conversation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversation"
  /conversations/types/{type}/{conversationId}/messages:
    post:
      tags:
        - Conversations
      operationId: addMessage
      summary: Add message to conversation
      parameters:
        - $ref: "#/components/parameters/ConversationType"
        - $ref: "#/components/parameters/ConversationId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddMessage"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /answers/types:
    get:
      tags:
        - "Answers"
      operationId: listAnswerTypes
      summary: List all answer types
      responses:
        200:
          description: List of answer types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AnswerOverview"
  /answers/types/{type}/respond:
    post:
      tags:
        - "Answers"
      operationId: generateAnswer
      summary: Generate an answer
      parameters:
        - $ref: "#/components/parameters/AnswerType"
      description: 1-off answer to questions.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Allow for different inputs for different answer types.
      responses:
        200:
          description: The generated answer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /content/search:
    get:
      tags:
        - "Content"
      operationId: search
      summary: Search for content
      parameters:
        - name: query
          in: query
          required: true
          description: The search query
          schema:
            type: string
        - name: dataSources
          in: query
          required: false
          description: The data sources to search
          schema:
            type: array
            items:
              type: string
        - name: format
          in: query
          required: false
          description: The format of the search result
          schema:
            type: string
        - name: lastUpdatedRange
          in: query
          required: false
          description: The range of last updated dates
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Timestamp"
              minItems: 2
              maxItems: 2
            examples:
              - [0, 1000000000000]
              - [1000000000000, 2000000000000]
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Offset"
      responses:
        200:
          description: List of search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContentResource"
      description: Perform search for related content.
  /content/data-sources:
    get:
      description: list all data sources with metadata
      operationId: listAllDataSources
      summary: List all data sources
      tags:
        - Content
      responses:
        200:
          description: List of data sources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DataSource"
  /content/data-sources/{dataSourceName}:
    get:
      tags:
        - Content
      parameters:
        - $ref: "#/components/parameters/DataSourceName"
      description: Get metadata for data source
      operationId: getDataSourceMetadata
      summary: Get metadata for a data source
      responses:
        200:
          description: Metadata for the data source
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataSource"
  /content/data-sources/{dataSourceName}/resources:
    get:
      description: Get all resources for a data source
      parameters:
        - $ref: "#/components/parameters/DataSourceName"
        - $ref: "#/components/parameters/Limit"
        - $ref: "#/components/parameters/Offset"
      operationId: getDataSourceResources
      tags:
        - Content
      summary: Get resources for a data source
      responses:
        200:
          description: List of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContentResource"
  /content/resources:
    get:
      operationId: getContentResources
      summary: Get content resources
      parameters:
        - $ref: "#/components/parameters/LastUpdated"
      description: Get resources that match certain filter criteria. With pagination.
      tags:
        - Content
      responses:
        200:
          description: List of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContentResource"
  /content/metadata:
    get:
      operationId: getContentMetadata
      summary: Get content metadata
      description: Lists different content types to help with filtering.
      tags:
        - Content
      responses:
        200:
          description: List of content Metadata filters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContentType"
components:
  parameters:
    AnswerType:
      name: type
      in: path
      required: true
      description: The type of answer to generate
      schema:
        type: string
    ConversationType:
      name: type
      in: path
      required: true
      description: The type of conversation to generate
      schema:
        type: string
    ConversationId:
      name: conversationId
      in: path
      required: true
      description: The ID of the conversation
      schema:
        type: string
    DataSourceName:
      name: dataSourceName
      in: path
      required: true
      description: The name of the data source
      schema:
        type: string
    LastUpdated:
      name: lastUpdated
      in: query
      required: false
      description: The last updated date of the content
      schema:
        $ref: "#/components/schemas/Timestamp"
    Limit:
      name: limit
      in: query
      required: false
      description: The number of results to return
      schema:
        type: integer
        format: int32
    Offset:
      name: offset
      in: query
      required: false
      description: The number of results to skip
      schema:
        type: integer
        format: int32

  schemas:
    AddMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          format: markdown
          description: |
            Markdown-formatted message from the user.
    AnswerOverview:
      type: object
      properties:
        type:
          type: string
          description: Type of answer
          example: "technical-content"
        description:
          type: string
          description: Description of the answer type
          example: "Generates a response based on the technical content."
        metadata:
          $ref: "#/components/schemas/ArbitraryMetadata"
    ArbitraryMetadata:
      type: object
      additionalProperties:
        type: string
    ContentResource:
      type: object
      properties:
        content:
          type: string
          description: The content of the search result
          examples:
            - "How to create a MongoDB Atlas cluster"
            - "https://mongodb.com/docs/some-image.png"
        dataSource:
          type: string
          description: The data source of the search result
          example: "MongoDB Documentation"
        uri:
          type: string
          description: The URI of the search result data.
        format:
          type: string
          description: |
            The format of the search result. Convention to follow the [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) format.
          format: MIME type
          examples:
            - "text/md"
            - "text/txt"
            - "image/png"
        lastUpdated:
          $ref: "#/components/schemas/Timestamp"
          description: Last updated date of the search result
        metadata:
          $ref: "#/components/schemas/ArbitraryMetadata"
    ContentType:
      type: object
      properties:
        name:
          type: string
          description: Name of the content type
          examples:
            - "contentType"
            - "lastUpdated"
            - "isLatestVersion"
        type:
          type: string
          description: Type of metadata
          examples:
            - "string"
            - "number"
            - "boolean"
        description:
          type: string
          description: Description of the content type
          example: "Technical content for the MongoDB documentation."
    Conversation:
      type: object
      required:
        - _id
        - messages
        - createdAt
      properties:
        _id:
          type: string
          description: The unique identifier for a conversation.
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        createdAt:
          type: integer
          description: Unix timestamp for when the conversation was created.
    Message:
      type: object
      required:
        - id
        - role
        - content
        - createdAt
      properties:
        id:
          type: string
          description: The unique identifier for a message.
        role:
          type: string
          enum:
            - user
            - assistant
        content:
          type: string
          format: markdown
          description: |
            Markdown-formatted response to user's chat message in the context
            of the conversation.
        rating:
          type: boolean
          description: >
            Set to `true` if the user liked the response, `false` if the user
            didn't like the response.

            No value if user didn't rate the response.


            Note that only messages with `role: "assistant"` can be rated.
        userComment:
          type: string
          description: >
            Comment from the user clarifying why they liked or disliked

            the message. No value if user didn't comment on the response.


            Note that only messages with `role: "assistant"` can be commented
            on.
        createdAt:
          type: integer
          description: |
            Unix timestamp for when the message was sent.
        references:
          $ref: "#/components/schemas/References"
    References:
      type: array
      description: |
        List of references to external resources that are relevant
        to the message. For example, if the message is a response to
        a user's question about how to connect, the list of
        references could include links to the documentation, dev
        center articles, or a video lesson on MongoDB University.
      items:
        type: object
        required:
          - title
          - url
        properties:
          title:
            type: string
            description: |
              Title of the reference. This is what shows up in
              rendered links. For example, "How to connect to
              MongoDB Atlas".
          url:
            type: string
            format: uri
            description: >
              URL to the reference. For example,
              "https://mongodb.com/docs/atlas/getting-started".

    ConversationOverview:
      type: object
      properties:
        type:
          type: string
          description: Type of conversation
          example: "docs-chatbot"
        description:
          type: string
          description: Description of the conversation type
          example: "Chat with the MongoDB technical documentation."
        metadata:
          $ref: "#/components/schemas/ArbitraryMetadata"
    DataSource:
      type: object
      properties:
        name:
          type: string
          description: Name of the data source
          example: "MongoDB Documentation"
        description:
          type: string
          description: Description of the data source
          example: "Technical documentation for MongoDB products."
        lastUpdated:
          type: number
          description: Last updated date of the data source
          format: timestamp
        metadata:
          $ref: "#/components/schemas/ArbitraryMetadata"
    OpenApiSpec:
      type: object
      description: An Open API specification
    Timestamp:
      type: number
      format: timestamp
  securitySchemes:
    NotPartOfSpec:
      type: apiKey
      name: NotPartOfSpec
      in: header
      description: Security schema is not part of the base Open Knowledge API specification.
